import os
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine


def database_url() -> str:
    explicit = os.getenv("DATABASE_URL")
    if explicit:
        return explicit
    host = os.getenv("DATABASE_HOST")
    if host:
        user = os.getenv("POSTGRES_USER", "student")
        password = os.getenv("POSTGRES_PASSWORD", "devpassword")
        database = os.getenv("POSTGRES_DB", "helpdesk")
        port = os.getenv("DATABASE_PORT", "5432")
        return f"postgresql+psycopg://{user}:{password}@{host}:{port}/{database}"
    return "sqlite:///helpdesk.db"


def get_engine() -> Engine:
    return create_engine(database_url(), future=True)


def initialize_database(engine: Engine) -> None:
    with engine.begin() as conn:
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS requests (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                title VARCHAR(200) NOT NULL,
                category VARCHAR(50) NOT NULL,
                priority VARCHAR(20) NOT NULL,
                description TEXT NOT NULL,
                status VARCHAR(30) NOT NULL DEFAULT 'Open',
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """ if engine.dialect.name != 'sqlite' else """
            CREATE TABLE IF NOT EXISTS requests (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                title TEXT NOT NULL,
                category TEXT NOT NULL,
                priority TEXT NOT NULL,
                description TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'Open',
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """))


def create_request(engine: Engine, title: str, category: str, priority: str, description: str) -> None:
    with engine.begin() as conn:
        conn.execute(text("""
            INSERT INTO requests (title, category, priority, description)
            VALUES (:title, :category, :priority, :description)
        """), {"title": title, "category": category, "priority": priority, "description": description})


def list_requests(engine: Engine):
    with engine.connect() as conn:
        rows = conn.execute(text("""
            SELECT id, title, category, priority, status, created_at
            FROM requests ORDER BY id DESC
        """)).mappings().all()
        return [dict(r) for r in rows]


def update_status(engine: Engine, request_id: int, status: str) -> None:
    with engine.begin() as conn:
        conn.execute(text("UPDATE requests SET status=:status WHERE id=:id"), {"status": status, "id": request_id})
